### ISSUE TITLE
Weapon Rack

### ISSUE THREAD

**Issue by Ollieollieolllie** [AH-64D-Apache-Official-Project/AH-64D#102]
**Aims**
a weapon rack on the right side of the seat that visibly shows the weapon equipped by the crew
similar to how transport vehicles show your rifle between your legs

**How do you envision this feature being implemented?**
Aboslutely no idea how it would be added

What modifications need to be made in order to provide the functionality 
a memory point for the weapons of the crew

**Comment by BradMick** [comment]
This would require the M4 mount to be modeled, textured and then added to the existing cockpit model. This is not likely going to happen.
