### ISSUE TITLE
Hitpoint Positions with ace Interaction repair

### ISSUE THREAD

**Issue by Ollieollieolllie** [AH-64D-Apache-Official-Project/AH-64D#109]
**Describe the bug**
 the Position of hitpoints under ace interaction repair

**Additional context**
for example, the left-wing hit point is on the tip of the wing, whereas the right-wing hitpoint is at the base of the wing
the verticle stab hitpoint is also at the base, the stabilizer hitpoint is on the tip 
and it goes on and on

**Comment by mattysmith22** [comment]
Is there any documentation on where ACE pulls its positioning information from?

**Comment by mattysmith22** [comment]
https://github.com/acemod/ACE3/blob/4d53d9ce4411b758bd07ae1daa61823d9407606d/addons/repair/functions/fnc_addRepairActions.sqf#L42-L44

Looking further into this, it looks like there are 2 config entries we can add to `configFile >> "CfgVehicles" >> "fza_ah64d_b2e"`: `"ace_repair_hitpointPositions"` and `"ace_repair_hitpointGroups"`. 

Inside the former is an array of pairs of hitpoint names and model coordinates.

Inside the latter is an array of pairs of a hitpoint name and array of child hitpoints that should be repaired by the parent.

Is this useful?
