### ISSUE TITLE
Point track Issues

### ISSUE THREAD

**Issue by Ollieollieolllie** [AH-64D-Apache-Official-Project/AH-64D#111]
**Describe the bug**
when using the point track key in multiplayer environment there can be up to a 2 second delay in between the keypress and the action of tracking/stop tracking, which in turn leads to oneself smashing the keys, leading to the camera spassing out for a solid minute

**To Reproduce**

1. multiplayer server
2. track and untrack targets

**Environments where the bug occurs**

* Multiplayer single-crew
* Multiplayer multi-crew

**Additional Info**
recommend we hide the key action until its fixed if we push to steam before its fixes

**Comment by mattysmith22** [comment]
Language.

**Comment by Ollieollieolllie** [comment]
this is no longer an issuie as the point tracking key no longer exists. and the FCR camera tracking works fine
