### ISSUE TITLE
Tads direction desync, breaking aiming cues

### ISSUE THREAD

**Issue by Ollieollieolllie** [AH-64D-Apache-Official-Project/AH-64D#114]
**Describe the bug**
in multiplayer multi crew the tads animation dose not track the gunner, it turn breaking the aim cues shown to the pilot, rocket cursor 

**To Reproduce**

1. play multiplayer after 10 ish minutes it might break

**Expected behavior**
the rocket aim cue will correctly show for the direction the tads shows, the issue is the tads animation does not follow the gunner

**Environments where the bug occurs**

Delete as appropriate

* Multiplayer multi-crew
* #172

**Comment by Ollieollieolllie** [comment]
needs more testing

**Comment by mattysmith22** [comment]
Who was this replicated with? Was it in a server between you and Fred? Or replicated across many instances?

Currently we base it off where the animation of the TADS is pointing. If that is too laggy, maybe we can look at saving the direction in variables and sending them to players as required.

I don't feel like that is very efficient network-wise though, so should be avoided if possible

**Comment by Ollieollieolllie** [comment]
tested with Fred & 1 other who joined us. occurs randomely happened to 3 different aircraft during said settin
2 were mulitcrew, 1 was fred on his lonesome
