### ISSUE TITLE
Pilot's magnetic "whiskey" compass is offset, has errors in display

### ISSUE THREAD

**Issue by PPooch** [AH-64D-Apache-Official-Project/AH-64D#120]
**Describe the bug**

The "whiskey" compass that is on the dash of the pilot's display has a couple errors. Firstly I noticed that the numbers "12" and "15" are reversed: the sequence should go E - 12 - 15 - S, however, it currently goes E - 15 - 12 - S. Also, there is no 3 (for 30 degrees) that prints in the whiskey compass. This makes the compass inaccurate.

**To Reproduce**

1. Turn clockwise in the air while observing the Apache's whiskey compass in the pilot's seat.

**Expected behavior**

Expected the whiskey compass to be accurate, and progress in a sequence of "N - 3 - 6 - E - 12 - 15 - S - 21 - 24 - W - 30 - 33"

**Screenshots**

![issue1](https://user-images.githubusercontent.com/42394661/133959933-b856c08e-7e37-400e-941d-08ce647f1169.png)
![issue2](https://user-images.githubusercontent.com/42394661/133959962-cb370abe-3623-4cc2-b303-630087a3b733.png)

**Environments where the bug occurs**
* Single-player
* Multiplayer single-crew
* Multiplayer multi-crew

**Reference material**

**Additional context**

I found the compass texture in fza_ah64_us/tex/In/Prime_co.paa . I would have attempted uploading a simple texture switch swapping the 12 and 15 myself, but the compass offset and missing "3" that is "off the edge" of whatever environment that is drawing the compass is beyond my ability.

![primeco](https://user-images.githubusercontent.com/42394661/133960422-0bbffd30-33eb-4c9a-9416-cda43eb25dc7.png)

The "3" is present in the source texture, but isn't drawn onto the compass in practice.

**Comment by SachaOropeza** [comment]
Well, that's a good finding ! Good catch, thanks.

**Comment by Ollieollieolllie** [comment]
got a texture fix in analog instruments pr
still requires a uv and model cfg change when able

**Comment by Ollieollieolllie** [comment]
#390
