### ISSUE TITLE
TSD Ownship Marker

### ISSUE THREAD

**Issue by Schlumpy28** [AH-64D-Apache-Official-Project/AH-64D#123]
**Aims**

Addition of Ownship marker to the TSD, this should be implemented so that the central dot is on the aircraft current position. 

**How do you envision this feature being implemented?**

-Addition of Ownship marker to `fn_mpdRTSDDraw.sqf`.
-Modification to `fn_mpdUpdatePoints.sqf` to allow for an offset value for _points array elements allowing Ownship to be centred on helicopter correctly.
-Creation of new Ownship texture which is a .paa in the DXT format.

**Reference material**

The Ownship icon can be found in the Public Intelligence AH-64D Operator's Manual

**Comment by Ollieollieolllie** [comment]
the use of a point for the sake of an ownership marker would not be an ideal fix, 
that being said this issue is Mute post mpd update

**Comment by Ollieollieolllie** [comment]
Fixed Post mpd
