### ISSUE TITLE
FCR not selectable as sensor source after adding from the vehicle garage

### ISSUE THREAD

**Issue by sevn10** [AH-64D-Apache-Official-Project/AH-64D#18]
This seems to only affect the no radar version of the Apache, so it may be a non-issue. If one of the Apaches with no radar is placed in Eden or Zeus but then the FCR is added in the vehicle garage the FCR will not actually be selectable as a sensor source when powered up.

**Comment by Ollieollieolllie** [comment]
issue lying with older iskind of statements trying to determine between radar and no radar version which is now outdated

**Comment by Ollieollieolllie** [comment]
close this, has been fixes in pr 21
https://github.com/AH-64D-Apache-Official-Project/AH-64D/pull/21/files
