### ISSUE TITLE
TSD scaling should be a pop-out menu and not a cycle option

### ISSUE THREAD

**Issue by mattysmith22** [AH-64D-Apache-Official-Project/AH-64D#188]
**Aims**
When you select the SC button on the TSD, rather than it cycling between sizes it should show a pop-out menu showing all scales on the right-hand VABS.

The default scale at system powerup should also be 1:250k (25km)

**How do you envision this feature being implemented?**

Modification to MFD config for dropdown to be added
Modification to script to allow for this selection state

**Reference material**

SC button - -10 page 3-72 (3.61.9)
Multi-state pushbutton design - -10 2-16 (Figure 2-17)

**Comment by Ollieollieolllie** [comment]
fixed in pr #328
