### ISSUE TITLE
B6 keybind is present for both MPD, but should not be.

### ISSUE THREAD

**Issue by unhappytroll** [AH-64D-Apache-Official-Project/AH-64D#214]
**Describe the bug**

Control keybinds for both MPD has B6 bind, which is clearly absent on MPD.

**To Reproduce**

1. Open Controls -> Keyboard -> AH-64 Apache Official: Cockpit Controls
2. Check listed keybinds.

**Expected behavior**

B6 keybinds for both MPD should be removed.

**Comment by mattysmith22** [comment]
Thank you for this bug report - I have confirmed that it is incorrect locally. I will look into fixing that now.

**Comment by mattysmith22** [comment]
The naming scheme has been modified to be consistent with the real aircraft & the lettering

![image](https://user-images.githubusercontent.com/9770674/211223542-d40e46a3-5f02-4092-b4bf-98958c6a6a43.png)

![image](https://user-images.githubusercontent.com/9770674/211223504-f94adae8-4c08-4d01-b1cc-819f3656098a.png)

Thank you for reporting this! Please keep us informed with any more issues you find.

**Comment by mattysmith22** [comment]
Correction on this: The order isn't "MENU", "B1", "B2", "B3", "B4", "B5". The first display pulls dual purpose as both the B1 key and the menu key. I forgot this, my bad.

We should still make this more evident to the user though. Maybe naming the key "B1/Menu" similiar to how figure 2-10 in the manual does
![image](https://user-images.githubusercontent.com/9770674/216483800-57e6a21c-8236-46f7-b924-3c95d4664fab.png)
