### ISSUE TITLE
Script missing for cockpit door interaction

### ISSUE THREAD

**Issue by sevn10** [AH-64D-Apache-Official-Project/AH-64D#22]
Using the most recent GitHub version of the AH-64D the cockpit doors both throw missing script errors when trying to interact with them. The are only openable or closeable via the scroll wheel interaction menu.

**Comment by Ollieollieolllie** [comment]
Close this has been fixed in pr 21
https://github.com/AH-64D-Apache-Official-Project/AH-64D/pull/21/files
