### ISSUE TITLE
Cannot select gunner/pilot weapon selection

### ISSUE THREAD

**Issue by Era4721** [AH-64D-Apache-Official-Project/AH-64D#229]
**Describe the bug**
In the pylon selection screen (through ace interact), 3/4 of the pylon options (for gunner/pilot access) are blocked by the button UI blocks, and cannot be clicked.

**To Reproduce**

1. Access the pylon screen through ace interact, try to switch access of the weapons to pilot or gunner

**Expected behavior**

Should be able to change access but can't

**Screenshots**

![Screenshot 2023-02-20 16-44-54](https://user-images.githubusercontent.com/34044294/220019569-781be6ec-0490-4669-b951-7e8150aa7d0e.png)

**Environments where the bug occurs**

Multiplayer (dedicated server)

**Comment by Ollieollieolllie** [comment]
While we plan to in the future add support for multi-crew weaponry in the current version of the apache is not compatible for, designed to or otherwise allow the pilot to use the weapons, its not perfect be we actually have a few funs that revert weapons to the gunner when they work

**Comment by Era4721** [comment]
That's unfortunate
