### ISSUE TITLE
Bug - no sound and animation for pilot.

### ISSUE THREAD

**Issue by Armybarmy101** [AH-64D-Apache-Official-Project/AH-64D#230]
**Describe the bug**

In live game with two men in it - whoever is flying gets sound and working model (rotor blades spinning etc.) - the gunner has no noise and the helicopter looks like it is switched off. When handing over controls - this then switches so that the pilot has no noise and animation but the gunner does.

**To Reproduce**

Play a live game with 2 players.

**Expected behavior**

Whoever has manual control over flying will have noises and animation - the gunner will not. 

* Multiplayer multi-crew

Thanks.

**Comment by Ollieollieolllie** [comment]
I have spoken with a few servers who use the mod and this is not an issue, as such it is likely a local issue, if you can find a way to first fix your issue then provide a more in-depth reproduction of the bug, we could look into this further

**Comment by mattysmith22** [comment]
@Armybarmy101 please can you try verifying integrity of the game and mod on all clients and the server?

* What is the modlist / does it persist with just the apache mod and the required dependencies?
* Are they all on the same modlist?
* How old is the mission? What happens in just a basic 3den mission with just the apache version?

**Comment by Ollieollieolllie** [comment]
No Responce to Questions, Unable to replicate, no corroborating players with this issue
closing
