### ISSUE TITLE
All sound are Played if shot by MANPAD

### ISSUE THREAD

**Issue by V1irus** [AH-64D-Apache-Official-Project/AH-64D#233]
Hi, yesterday I encountered an error/bug.

We got locked and shot by a MANPAD then script error and all sound playing at once. 

It happened in Multiplayer mulicrew and reproduced in Singleplayer. 

Error in RDP: 

17:31:16 Error in expression <ystem == "")) then {
playSound _system;
sleep _delay1;
};
if (!(_subsystem == "">
17:31:16   Error position: <sleep _delay1;
};
if (!(_subsystem == "">
17:31:16   Error Suspending not allowed in this context
17:31:16 File fza_ah64_controls\scripting\functions\fn_playAudio.sqf..., line 65
17:31:16 Error in expression <em == "")) then {
playSound _subsystem;
sleep _delay2;
};
if (!(_state == "")) t>
17:31:16   Error position: <sleep _delay2;
};
if (!(_state == "")) t>
17:31:16   Error Suspending not allowed in this context
17:31:16 File fza_ah64_controls\scripting\functions\fn_playAudio.sqf..., line 69
17:31:16 Error in expression <_state == "")) then {
playSound _state;
sleep _delay3;
};

fza_ah64_bt_soundplay>
17:31:16   Error position: <sleep _delay3;
};

fza_ah64_bt_soundplay>
17:31:16   Error Suspending not allowed in this context
17:31:16 File fza_ah64_controls\scripting\functions\fn_playAudio.sqf..., line 73

**Comment by Ollieollieolllie** [comment]
This is being addressed currently
-steam update soon TM
