### ISSUE TITLE
Script error when spawn in Zeus

### ISSUE THREAD

**Issue by V1irus** [AH-64D-Apache-Official-Project/AH-64D#234]
**Describe the bug**

0:55:35 Error in expression <.0;
private _maxTotFuelMass = 0.0;

if (_IAFSInstalled) then {
_maxTotFuelMass =>
 0:55:35   Error position: <_IAFSInstalled) then {
_maxTotFuelMass =>
 0:55:35   Error Undefined variable in expression: _iafsinstalled
 0:55:35 File fza_ah64_sfmplus\functions\fuel\fn_fuelSet.sqf..., line 36
 0:55:35 Error in expression <.0;
private _maxTotFuelMass = 0.0;

**To Reproduce**

if you spawn a AH-64 in Zeus

**Expected behavior**

no error

**Screenshots**

N.A.
**Environments where the bug occurs**

Delete as appropriate

* Multiplayer single-crew
* Multiplayer multi-crew

**Comment by Ollieollieolllie** [comment]
Local Integrity Issuie, your version of the mod is partially broken, try repairing your mod
- Cant reproduce
