### ISSUE TITLE
Error thrown in multiplayer during briefing

### ISSUE THREAD

**Issue by mattysmith22** [AH-64D-Apache-Official-Project/AH-64D#241]
**Describe the bug**

In multiplayer, it is possible for errors to be thrown in the briefing stage of multiplayer missions

**To Reproduce**

1. Create an arma 3 mission with the following requirements
    * Briefing enabled
    * Pilots start *in the aircraft*
2. Load the mission on a server
3. Take one of the pilots slots
4. Start the mission into the briefing

**Expected behavior**

An error shouldn't be thrown

**Screenshots**

![20230423142344_1](https://user-images.githubusercontent.com/9770674/233872977-0fe37b3f-84d1-455e-89ef-52833815612d.jpg)

**Environments where the bug occurs**

* Multiplayer single-crew
* Multiplayer multi-crew

**Additional context**

Seems to be linked to [CBA settings](https://cbateam.github.io/CBA_A3/docs/files/settings/fnc_addSetting-sqf.html#CBA_fnc_addSetting), maybe they aren't defined at the init stage in briefing?

Is there a way to make this part of the script run after the briefing?

**Comment by Ollieollieolllie** [comment]
fixed in PR #399
