### ISSUE TITLE
Helisim Still recognised mouse in freelook/spectator/zues

### ISSUE THREAD

**Issue by Ollieollieolllie** [AH-64D-Apache-Official-Project/AH-64D#298]
**To Reproduce**
1. hold or tab freelook and move mouse

**Expected behavior**
 helicopter will recognise inputs

**Expected behavior**
hold or tab freelook and move mouse, helicopter will still recognise inputs

**Environments where the bug occurs**
* Single-player
* Multiplayer single-crew
* Multiplayer multi-crew

**Solution** 
https://community.bistudio.com/wiki/freeLook

**Comment by BradMick** [comment]
Fixed
