### ISSUE TITLE
Engine info for gunner

### ISSUE THREAD

**Issue by Ollieollieolllie** [AH-64D-Apache-Official-Project/AH-64D#32]
on at least AFM Engine info cannot be seen by gunner

**Comment by mattysmith22** [comment]
This is primarily done due to performance - the heli simulation info is not transmitted across the network by arma, so we would  need to do it ourselves.

It would probably make sense to put better placeholder data though.

**Comment by Ollieollieolllie** [comment]
Fixed in sfm+
