### ISSUE TITLE
Simple rotor error

### ISSUE THREAD

**Issue by Ollieollieolllie** [AH-64D-Apache-Official-Project/AH-64D#320]
**Describe the bug**
When helisim is placed in eden, error appears

**To Reproduce**

1. Launch eden editor
2. place Helisim

**Expected behavior**
Error Appears

**Screenshots**
```
23:31:49 Error in expression <rtrTorqueScalar) * _deltaTime);
_heli addForce [_heli vectorModelToWorld _thru>
23:31:49   Error position: <addForce [_heli vectorModelToWorld _thru>
23:31:49   Error 0 elements provided, 3 expected
23:31:49 File fza_ah64_sfmplus\functions\simpleRotor\fn_simpleRotor.sqf..., line 94
```

**Environments where the bug occurs**
* Single-player

**Comment by BradMick** [comment]
I am not able to reproduce this at all. I’ve placed multiple HeliSim Apaches a day for the last several months with no errors in the mission editor.
