### ISSUE TITLE
FCR acquisition realism 

### ISSUE THREAD

**Issue by Ollieollieolllie** [AH-64D-Apache-Official-Project/AH-64D#33]
The FCR never forgets targets once it acquires them

**Comment by mattysmith22** [comment]
At some point I would like to more closely represent how the real FCR works, but until we have some persistent way of storing targets (Targets, waypoints, control measures) I don't want to remove its persistence fully.

**Comment by Ollieollieolllie** [comment]
Fixed in pr #66
