### ISSUE TITLE
Avionics indicate FCR presence even with it removed

### ISSUE THREAD

**Issue by Ollieollieolllie** [AH-64D-Apache-Official-Project/AH-64D#37]
even when the radar is not equipped the pilots can Ctrl + R like there turning on the radar and the wipers on the ihadss and fcr page will sweep

**Comment by mattysmith22** [comment]
The FCR indicators in both the HAD and the heading tape of the IHADSS should just not be present if the FCR isn't installed.

The wiper should not be present in the apache's FCR page. It should just be a blank version of the ground mode with "FCR Not Installed" written in the centre. It should probably be done as just another background texture.

**Comment by Ollieollieolllie** [comment]
fixed in pr #44
