### ISSUE TITLE
Broken shotatvariable

### ISSUE THREAD

**Issue by Ollieollieolllie** [AH-64D-Apache-Official-Project/AH-64D#38]
Removes target from shotatlist variable not working
if you shoot a missile and the missile fail to kill it the shot at icon should revert to the target icon 
the issue is with shotatlist

maybe give each item in the list a time and remove it after so long

**Comment by mattysmith22** [comment]
I think this works differently to how it works in the mod anyway (the shotat thing doesn't replace the target, it shows where hellfires have been previously shot at.) We'll see what we can find, though this might be an MPD rewrite thing.

**Comment by Ollieollieolllie** [comment]
Not an issue as it real thing
