### ISSUE TITLE
PNVS controls

### ISSUE THREAD

**Issue by Ollieollieolllie** [AH-64D-Apache-Official-Project/AH-64D#56]
using the pnvs at night & when using the overlay can be disorientating as the pnvs does not look in the same direction as the pilot

link pnvs to sight select possibley
or just make it look where pilot looks

**Comment by mattysmith22** [comment]
PNVS should not follow sight select. Could look at using [`eyeDirection`](https://community.bistudio.com/wiki/eyeDirection) to drive the pos
