### ISSUE TITLE
CP/G Unable to interact in MP 

### ISSUE THREAD

**Issue by xSlykiller** [AH-64D-Apache-Official-Project/AH-64D#610]
**Describe the bug**
When in MP, CP/G pilot is unable to interact with anything. 

**To Reproduce**
1. Player in PIC seat
2. Player in CP/G seat

**Expected behavior**
Being able to interact with the buttons and switches and shit

**Screenshots**
N/A

**Environments where the bug occurs**

* Multiplayer multi-crew

**Comment by mattysmith22** [comment]
Thanks for identifying this issue. I think this may have been caused by this PR #596. Our dev branch on steam hadn't been updated  since then, so if you try again now it may be fixed. Please could you either build master locally, or re-test on dev branch on steam?

**Comment by xSlykiller** [comment]
Issue resolved in current Steam Development Branch of the project.
