### ISSUE TITLE
HeliSim Spinning and Launching upon entering pilot seat. 

### ISSUE THREAD

**Issue by xSlykiller** [AH-64D-Apache-Official-Project/AH-64D#636]
**Describe the bug**

HeliSim version spins and sometimes launches into orbit when getting into the pilot seat during multiplayer sessions. 

**To Reproduce**

1. Spawn HeliSim version on a MP server with other players. 
2. Get into pilot seat
3. Buckle your seatbelt and pray you dont get launched. 

**Expected behavior**

I expect to get into the aircraft and not become a cosmonaut. 

**Screenshots**

N/A

**Environments where the bug occurs**

Delete as appropriate

* Multiplayer single-crew
* Multiplayer multi-crew

**Comment by xSlykiller** [comment]
https://github.com/user-attachments/assets/69025147-5322-48e9-bf63-3d8b9aad792e

**Comment by xSlykiller** [comment]
https://github.com/user-attachments/assets/5d0a6766-ddc3-4583-befe-c5e66c5ccd35

**Comment by Ollieollieolllie** [comment]
possible fix #640

**Comment by Ollieollieolllie** [comment]
believed to be fixed with pr #641
