### ISSUE TITLE
Master Caution Triggered when CP/G enters aircraft 

### ISSUE THREAD

**Issue by xSlykiller** [AH-64D-Apache-Official-Project/AH-64D#638]
**Describe the bug**

When the Co-pilot enters the CP/G seat after the backseat pilot has activated the APU, then a master caution is triggered. 

**To Reproduce**

1. PIC starts the APU and the CP/G remains outside the aircaft
2. After APU has fully turned on, copilot enters the CP/G seat
3. Enjoy the leedle leedle. 

**Expected behavior**

My expectation is that when the copilot enters the CP/G seat, the master caution should not be triggered before the CP/G has a chance to touch anything. 

**Screenshots**

**Environments where the bug occurs**

Delete as appropriate

* Multiplayer multi-crew

**Reference material**

N/A

**Additional context**
In the video provided, the backseat pilot was instructed upon entering the aircraft to only start the APU and no other systems. 

https://github.com/user-attachments/assets/abbf1b62-c2df-446e-9bde-f1aef229cbdb

**Comment by xSlykiller** [comment]
Additional note: Bug occurs in SFM+ and HeliSim versions.

**Comment by Ollieollieolllie** [comment]
CAUSE - PRI & UTIL Hydraulics flag for a single frame on Getin

**Comment by Ollieollieolllie** [comment]
Fixed in pr #644
