### ISSUE TITLE
Rockets not accurate anymore

### ISSUE THREAD

**Issue by Ollieollieolllie** [AH-64D-Apache-Official-Project/AH-64D#69]
rockets always hit  low/high of aim point 
might be due to low animation refresh of the rocket pod
or bad rocket artillery table

**Comment by mattysmith22** [comment]
I tried to increase the animation refresh rate - the animate command runs every frame if I remember correctly!

Maybe we have to make it snap between the points? Feel free to have a play!

**Comment by Ollieollieolllie** [comment]
i think the rocket table just needs more values & to be recalibrated (so 3500 is this value, not current ect)

**Comment by Ollieollieolllie** [comment]
also the refresh rate might have been lower on the older version
