### ISSUE TITLE
Vehicle Customisation resets animations

### ISSUE THREAD

**Issue by mattysmith22** [AH-64D-Apache-Official-Project/AH-64D#77]
The function used by Arma 3's vehicle customisation system ([`bis_fnc_initVehicle`](https://community.bistudio.com/wiki/BIS_fnc_initVehicle)) resets every single animation to its `initPhase`, even if it is not on the vehicle customisation menu.

This leads to doors being reset, but more importantly it also resets `plt_batt` and `plt_apu`. We have no way of preventing these from being reset, so we should probably move the mission-essential values off the animation.

Maybe do this on a public `setVariable`?

**Comment by mattysmith22** [comment]
We could also look at adding opening and closing the doors as options on the vehicle customisation!

**Comment by Ollieollieolllie** [comment]
Me & Brad both agree going into the garage is the equivalent of refitting the aircraft, meaning turning it off

**Comment by mattysmith22** [comment]
The primary issue with it isn't that it resets the systems, but that it only half does so. All the animations reset, but the variables don't.

I don't mind the reset, the mismatch is the issue. the easiest way to fix it is to move all the stuff on aminations to variables, and then make the animations follow the value of the variables

**Comment by mattysmith22** [comment]
![image](https://user-images.githubusercontent.com/9770674/151684710-190297fd-0583-4158-ab62-d301125217c4.png)

Design plan as discussed by @BradMick and I
