### ISSUE TITLE
Hellfire Jitter/Inaccuracy

### ISSUE THREAD

**Issue by ZweiProbleme** [AH-64D-Apache-Official-Project/AH-64D#88]
This appears to happen only with the SAL versions of the Hellfires using TADS LRFD (and possibly an independent laser designator).

Once locked and fired, regardless of selected trajectory, the Hellfires will assume a direct trajectory and wildly flail out of control as they approach the target. This often causes them to miss or near-miss. This happens both in MP and SP.

The selected trajectory doesn't seem to matter for the "expected" flight path itself, but selecting "HIGH" will often lead to it completely missing the target and veering right, despite the LRFD not moving whatsoever.

I'm unsure if there's a difference in versioning between Github and Steam, but this is using the Steam version.

**Comment by Ollieollieolllie** [comment]
fix in pr #95

**Comment by mattysmith22** [comment]
We have made some changes to how hellfire guidance works, it should now not oversteer as much as it was
