### ISSUE TITLE
Pilot Sight Zoom In Problem

### ISSUE THREAD

**Issue by amitai12** [AH-64D-Apache-Official-Project/AH-64D#91]
Hey, when I'm sitting in the cockpit activating the sight and trying to zoom in it does not seem like it is possible.
And difficult and even impossible to clearly see at a distance of more than 200 meters from the helicopter. Is it intentional that there is no zoom in or that certain keys may need to be set?
Thanks

**Comment by BradMick** [comment]
This is not an actual feature on the aircraft and was removed. It is not a bug.

**Comment by amitai12** [comment]
So if i play on SP and can’t really trust the AI gunner that will be enough
efficient, I can’t find targets in the distance by myself?
What the reason you are removed this important feature?

**Comment by RacerXx** [comment]
ok this decision is game breaking. I have a AI gunner and i need to be able to zoom in to see targets. If it was removed can you please instruct us how to put it back in or turn it on? I know how to get into pbo's use notepad to edit. I need the code and the file to insert it in
