### ISSUE TITLE
Folded rotor state

### ISSUE THREAD

**Issue by Ollieollieolllie** [AH-64D-Apache-Official-Project/AH-64D#98]
**Aims**
to add an animation garage state of the rotors folded to show it in a stored state as a decorative peice in a hanger or also having a scroll wheel option to fold/unfold the rotors mid-mission 

**How do you envision this feature being implemented?**
an animation the folds the rotors or simply a model element with the rotors folded that are hidden and unhidden when needed

**Reference material**
![Apache-blade-fold-and-restraint-01](https://user-images.githubusercontent.com/60583203/126834404-8c14c767-bed9-437c-8dc1-20142195619c.jpg)
![download](https://user-images.githubusercontent.com/60583203/126834405-87d7a68d-2e8a-48b4-b30f-646a2739c2ce.jpg)
![unnamed](https://user-images.githubusercontent.com/60583203/126834407-38858fc3-10e6-4f0e-bc5e-5b5b046eab3b.jpg)
![AH-64-New-Folding-Kit](https://user-images.githubusercontent.com/60583203/126834408-866f13ad-bb64-49e9-a8c8-10fe7c2eaf3b.jpg)
![8eae531f234106326abfe9845bac1a74](https://user-images.githubusercontent.com/60583203/133910434-fc15ff36-f942-466c-9ce6-c1869a4ca70c.png)
![4014bedd695047621e9e92358a574e65](https://user-images.githubusercontent.com/60583203/133910435-aa0c0021-f752-4a82-bd1d-209b41c92588.png)

**Comment by BradMick** [comment]
This isn't a common thing. The only time this is done is when the aircraft is being transported via a cargo aircraft.
